extension_dir="ext"

extension=pdo_sqlite
extension=sqlite3
extension=zip
extension=mbstring
extension=fileinfo

; (opcionais, mas ok manter)
extension=xml
extension=dom

date.timezone=America/Sao_Paulo
